- platform: rest
  scan_interval: 1
  name: mutedeck
  resource: http://192.168.86.189:3491/v1/status
  json_attributes:
    - call
    - control
    - mute
    - record
    - share
    - status
    - video
