sensor:
  - platform: rest
    name: Ynab
    headers: 
      Authorization: !secret ynab_token 
    json_attributes:
      - kath_spending
      - ross_spending
    resource: https://api.youneedabudget.com/v1/budgets/8ab7902c-bb25-46f9-94fd-676406987be1/categories
    value_template: '{% for value in my_test_json.data.category_groups %}{% if value.id == "0df76b69-c12c-413e-bda7-fc0fd967af2c"%} {{ value.categories | sum(attribute='balance') }}{% endif %}{% endfor %}'
  - platform: template
    sensors:
      kath_spending:
        friendly_name: 'Kath Spending'
        value_template: '{% for value in my_test_json.data.category_groups %}{% if value.id == "28c911f6-c796-4ab1-bac8-e4e2bd546747"%} {{ value.categories | sum(attribute='balance') }}{% endif %}{% endfor %}'
      ross_spending:
        friendly_name: 'Ross Spending'
        value_template: '{% for value in my_test_json.data.category_groups %}{% if value.id == "8c2bd62c-9d7e-4f20-b8ff-18c36362eea1"%} {{ value.categories | sum(attribute='balance') }}{% endif %}{% endfor %}'
