homeassistant:  
 # name: Home  
 # latitude: !secret latitude
 # longitude: !secret longitude  
 # elevation: 30
 # unit_system: metric  
 # time_zone: Europe/London
  customize: !include configuration/customize.yaml  
  packages: !include_dir_named configuration/packages/
  allowlist_external_dirs: 
   - /snapshots/

frontend:
  themes: !include_dir_merge_named ./themes
###################################################################################
# Standard configuration
###################################################################################
#emulated_roku:1
#  host_ip: 192.168.86.10 # should be set to Home Assistant's address
default_config:

cloud:
auth:

###################################################################################
# Group configurations
###################################################################################
automation: !include automations.yaml
alexa: !include configuration/alexa/alexa.yaml
alert: !include_dir_merge_named configuration/alert
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include configuration/groups.yaml
intent_script: !include_dir_merge_named configuration/alexa/intent_script/ 
media_player: !include_dir_merge_list configuration/media_player
mqtt: 
  binary_sensor: !include_dir_merge_list configuration/mqtt/binary_sensor
  sensor: !include_dir_merge_list configuration/mqtt/sensor
notify: !include configuration/notify.yaml
# panel_iframe: !include configuration/panel_iframe.yaml
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensors
switch: !include_dir_merge_list configuration/switches
template: !include_dir_merge_list configuration/template
zone: !include configuration/zones.yaml

####################################################################################
# Additional Configurations
####################################################################################
#homekit:
  #pincode: !secret homekit
  #entity_config:
  #  alarm_control_panel.ha_alarm:
      #code: !secret pin
  #filter:
  #  exclude_domains:
  #    - automation
  #  exclude_entities:
  #    - binary_sensor.greenhouse_resevoir

#apcupsd:
#  host: 192.168.86.10
  
#custom_updater:
#  component_urls:
#  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
#  - https://raw.githubusercontent.com/custom-components/information/master/repos.json
#  - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

calendar:
  - platform: todoist
    token: !secret todoist
    
rest_command:
  garden_event_door_open:
    url: "https://frigate.dargan.uk/api/events/garden/Door Opened/create"
    method: post
    content_type: "application/json"
    payload: '{"duration": 30, "include_recording": true }'
   
http: 
 ip_ban_enabled: true
 login_attempts_threshold: 2
 trusted_proxies: 172.18.0.18
 use_x_forwarded_for: true
 
light:
  - platform: switch
    name: Kitchen Outer Light
    entity_id: switch.kitchen_outer_lights_switch
  - platform: switch
    name: Playroom Main Light
    entity_id: switch.playroom_main_light
  - platform: switch
    name: Landing Light
    entity_id: switch.landing_light
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_main_light
      - light.kitchen_outer_light

plant:
  chillies:
    sensors:
      temperature: sensor.greenhouse_temperature
      brightness: sensor.greenhouse_light
    min_temperature: 5
    
proximity:
  home:    
    devices:
        - device_tracker.lya_l09
    tolerance: 50
    unit_of_measurement: mi

powercalc:
  scan_interval: 00:01:00 #Each minute
  power_sensor_naming: "{} Powersensor"
  
recorder:  
  purge_keep_days: 10
  db_url: !secret maria_db
  exclude:
   entities:
    - sensor.house_energy_5624021b_smartenergy_metering
    - sensor.house_energy_5624021b_smartenergy_metering_summation_delivered
downloader:
 download_dir: /snapshots/

tplink:    

tts:
  - platform: microsoft
    api_key: !secret microsoft_tts_key

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

weather:
  - platform: darksky
    api_key: !secret darksky
  

influxdb:
  host: 192.168.86.51
  api_version: 2
  ssl: false
  port: 8086
  token: !secret influxdb_token
  organization: 8e90e1f1bec1671f
  bucket: homeassistant
  

hacs:
  token: !secret git_token


withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret

input_boolean:
  winter:
    name: Disable the greenhouse alerts in the winter
    icon: mdi:thermometer-chevron-down
    
input_number:
  kitchen_light_level:
    name: Kitchen light level
    min: 0
    max: 150
    step: 1    
    unit_of_measurement: 'lx'
  hall_light_level:
    name: Hall light level
    min: 0
    max: 150
    step: 1    
    unit_of_measurement: 'lx'    

input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'

shell_command:
  update_ha: "echo '/docker/homeassistant/up.sh' > cmdpipe"
  restart_ha: "echo 'docker restart home-assistant' > cmdpipe"
  pull_config: "echo '/docker/homeassistant/pull.sh' > cmdpipe"
  todays_timelapse: "echo '/docker/timelapse/today.sh' > cmdpipe"

proxmoxve:
  - host: 192.168.86.11
    username: hass@pve
    password: !secret pve
    verify_ssl: false
    nodes:
      - node: pve
        vms:
          - 103
        containers:
          - 100
          - 101
          - 104

    
logger:
  default: warning
  logs:
    custom_components.powercalc: debug

zha:
  zigpy_config:
    ota:
      ikea_provider: true
      inovelli_provider: true
      ledvance_provider: true
      salus_provider: true
      sonoff_provider: true
      thirdreality_provider: true
