homeassistant:  
  name: Home  
  latitude: !secret latitude
  longitude: !secret longitude  
  elevation: 30
  unit_system: metric  
  time_zone: Europe/London
  customize: !include configuration/customize.yaml  
  packages: !include_dir_named configuration/packages/

###################################################################################
# Standard configuration
###################################################################################
#emulated_roku:
#  host_ip: 192.168.86.10 # should be set to Home Assistant's address
default_config:

cloud:
ios:
auth:

###################################################################################
# Group configurations
###################################################################################
automation: !include_dir_merge_list configuration/automation
alexa: !include configuration/alexa/alexa.yaml
alert: !include_dir_merge_named configuration/alert
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include configuration/groups.yaml
intent_script: !include_dir_merge_named configuration/alexa/intent_script/ 
media_player: !include_dir_merge_list configuration/media_player
notify: !include configuration/notify.yaml
panel_iframe: !include configuration/panel_iframe.yaml
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensors
timer: !include configuration/timer.yaml
zone: !include configuration/zones.yaml

####################################################################################
# Additional Configurations
####################################################################################
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

homekit:
  pincode: !secret homekit
  entity_config:
    alarm_control_panel.alarm:
      code: !secret pin
  filter:
    exclude_domains:
      - automation
    exclude_entities:
      - binary_sensor.greenhouse_resevoir

apcupsd:
  host: 192.168.86.10
camera:
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil08.jpg?
    name: A1
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil13.jpg?
    name: 'Sniperley Roundabout'
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil12.jpg?  
    name: 'Dryburn Park'    
  - platform: ring
  
#custom_updater:
#  component_urls:
#  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
#  - https://raw.githubusercontent.com/custom-components/information/master/repos.json
#  - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
  
calendar:
  - platform: todoist
    token: !secret todoist
    
device_tracker:
#  - platform: owntracks
#    secret: !secret owntracks
  - platform: icloud
    username: !secret apple_username
    password: !secret apple_password
    account_name: Apple
  - platform: google_maps
    username: !secret google_username

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html

history_graph:
  temp:
    name: Temperature Graph
    entities:
      - sensor.greenhouse_temperature
      - sensor.hall_temperature
    hours_to_show: 48
    refresh: 60
    
http:
 api_password: !secret api_password
 ip_ban_enabled: true
 login_attempts_threshold: 2
 trusted_proxies: 192.168.86.51
 use_x_forwarded_for: true
 
light:
  - platform: group
    name: Lounge Lights
    entities:
      - light.lounge_iris
      - light.lounge_main_light_level
      - light.lounge
mqtt:
  broker: 192.168.86.51
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

plant:
  chillies:
    sensors:
      temperature: sensor.greenhouse_temperature
      brightness: sensor.greenhouse_light
    min_temperature: 5
    
    
recorder:  
  purge_keep_days: 2 
  db_url: !secret sql
ring:
  username: !secret ring_username
  password: !secret ring_password
  
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

tplink:    

transmission:
  host: !secret seedbox
  username: !secret transmission_username
  password: !secret transmission_password
  monitored_conditions:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    
tts:
  - platform: microsoft
    api_key: !secret microsoft_tts_key

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_key

weather:
  - platform: darksky
    api_key: !secret darksky
  

influxdb:
  host: 192.168.86.51
  database: homeassistant

hacs:
  token: !secret git_token
  