homeassistant:  
 # name: Home  
 # latitude: !secret latitude
 # longitude: !secret longitude  
 # elevation: 30
 # unit_system: metric  
 # time_zone: Europe/London
  customize: !include configuration/customize.yaml  
  packages: !include_dir_named configuration/packages/
  allowlist_external_dirs: configuration/snapshots/

frontend:
  themes: !include_dir_merge_named ./themes
###################################################################################
# Standard configuration
###################################################################################
#emulated_roku:1
#  host_ip: 192.168.86.10 # should be set to Home Assistant's address
default_config:

cloud:
auth:

###################################################################################
# Group configurations
###################################################################################
automation: !include automations.yaml
alexa: !include configuration/alexa/alexa.yaml
alert: !include_dir_merge_named configuration/alert
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include configuration/groups.yaml
intent_script: !include_dir_merge_named configuration/alexa/intent_script/ 
media_player: !include_dir_merge_list configuration/media_player
notify: !include configuration/notify.yaml
# panel_iframe: !include configuration/panel_iframe.yaml
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensors
template: !include_dir_merge_list configuration/template
zone: !include configuration/zones.yaml

####################################################################################
# Additional Configurations
####################################################################################
#homekit:
  #pincode: !secret homekit
  #entity_config:
  #  alarm_control_panel.ha_alarm:
      #code: !secret pin
  #filter:
  #  exclude_domains:
  #    - automation
  #  exclude_entities:
  #    - binary_sensor.greenhouse_resevoir

#apcupsd:
#  host: 192.168.86.10
camera:
  - platform: generic
    still_image_url: https://dcc.ussgroup.co.uk/images/dutmc_42.jpg
    name: 'Sniperley Roundabout'
  - platform: generic
    still_image_url: https://dcc.ussgroup.co.uk/images/dutmc_27.jpg?
    name: 'Dryburn Park' 
  
#custom_updater:
#  component_urls:
#  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
#  - https://raw.githubusercontent.com/custom-components/information/master/repos.json
#  - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

calendar:
  - platform: todoist
    token: !secret todoist
    

   
http: 
 ip_ban_enabled: true
 login_attempts_threshold: 2
 trusted_proxies: 172.28.0.6
 use_x_forwarded_for: true
 
light:
  - platform: switch
    name: Kitchen Outer Light
    entity_id: switch.kitchen_outer_lights_switch
  - platform: switch
    name: Playroom Main Light
    entity_id: switch.playroom_main_light
  - platform: switch
    name: Landing Light
    entity_id: switch.landing_light
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_main_light
      - light.kitchen_outer_light
  - platform: group
    name: Lounge Lights
    entities:
      - light.lounge_iris
      - light.lounge_main_light_level
      - light.lounge
  - platform: group
    name: Dining Room Main Light
    entities:
      - light.color_temperature_light_1
      - light.color_temperature_light_2
      - light.color_temperature_light_3

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

plant:
  chillies:
    sensors:
      temperature: sensor.greenhouse_temperature
      brightness: sensor.greenhouse_light
    min_temperature: 5
    
proximity:
  home:    
    devices:
        - device_tracker.lya_l09
    tolerance: 50
    unit_of_measurement: mi
              
recorder:  
  purge_keep_days: 10
  db_url: !secret maria_db
  exclude:
   entities:
    - sensor.house_energy_5624021b_smartenergy_metering
    - sensor.house_energy_5624021b_smartenergy_metering_summation_delivered


tplink:    

tts:
  - platform: microsoft
    api_key: !secret microsoft_tts_key

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

weather:
  - platform: darksky
    api_key: !secret darksky
  

#influxdb:
#  host: 192.168.86.51
#  api_version: 2
#  ssl: false
#  port: 8086
#  token: !secret influxdb_token
#  organization: 3d066bf523ef93fc
#  bucket: homeassistant
  

hacs:
  token: !secret git_token

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret


withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret

input_boolean:
  winter:
    name: Disable the greenhouse alerts in the winter
    icon: mdi:thermometer-chevron-down
    
input_number:
  kitchen_light_level:
    name: Kitchen light level
    min: 0
    max: 150
    step: 1    
    unit_of_measurement: 'lx'
  hall_light_level:
    name: Hall light level
    min: 0
    max: 150
    step: 1    
    unit_of_measurement: 'lx'    

input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'

shell_command:
  update_ha: "echo '/docker/homeassistant/up.sh' > cmdpipe"
  restart_ha: "echo 'docker restart home-assistant' > cmdpipe"
  pull_config: "echo '/docker/homeassistant/pull.sh' > cmdpipe"
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

proxmoxve:
  - host: 192.168.86.11
    username: hass@pve
    password: !secret pve
    verify_ssl: false
    nodes:
      - node: pve
        vms:
          - 103
        containers:
          - 100
          - 101
          - 104
switch:
  platform: hadockermon
  host: 192.168.86.53
  port: 8126
  stats: true
  prefix: dockermedia
  exclude:
    - 'ha-dockermon'
          
switch:
  platform: hadockermon
  host: 192.168.86.51
  port: 8126
  stats: true
  prefix: dockerauto
  exclude:
    - 'ha-dockermon'
sensor:
  - platform: tautulli
    api_key: !secret tautulli
    host: 192.168.86.53
    
logger:
  default: info
