homeassistant:  
  name: Home  
  latitude: !secret latitude
  longitude: !secret longitude  
  elevation: 30
  unit_system: metric  
  time_zone: Europe/London
  customize: !include configuration/customize.yaml  
  packages: !include_dir_named configuration/packages/

frontend:
  themes: !include_dir_merge_named ../themes
###################################################################################
# Standard configuration
###################################################################################
#emulated_roku:
#  host_ip: 192.168.86.10 # should be set to Home Assistant's address
default_config:

cloud:
ios:
auth:

###################################################################################
# Group configurations
###################################################################################
automation: !include_dir_merge_list configuration/automation
alexa: !include configuration/alexa/alexa.yaml
alert: !include_dir_merge_named configuration/alert
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include configuration/groups.yaml
intent_script: !include_dir_merge_named configuration/alexa/intent_script/ 
media_player: !include_dir_merge_list configuration/media_player
notify: !include configuration/notify.yaml
panel_iframe: !include configuration/panel_iframe.yaml
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensors
zone: !include configuration/zones.yaml

####################################################################################
# Additional Configurations
####################################################################################
homekit:
  pincode: !secret homekit
  entity_config:
    alarm_control_panel.ha_alarm:
      code: !secret pin
  filter:
    exclude_domains:
      - automation
    exclude_entities:
      - binary_sensor.greenhouse_resevoir

apcupsd:
  host: 192.168.86.10
camera:
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil08.jpg?
    name: A1
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil13.jpg?
    name: 'Sniperley Roundabout'
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil12.jpg?  
    name: 'Dryburn Park' 
  
#custom_updater:
#  component_urls:
#  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
#  - https://raw.githubusercontent.com/custom-components/information/master/repos.json
#  - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

calendar:
  - platform: todoist
    token: !secret todoist
    
device_tracker:
  - platform: huesensor
#  - platform: owntracks
#    secret: !secret owntracks
  - platform: icloud
    username: !secret apple_username
    password: !secret apple_password
    account_name: Apple
  - platform: nmap_tracker
    home_interval: 10
    hosts: 
      - 192.168.86.23 # Me
      - 192.168.86.60 # Adam
   
http: 
 ip_ban_enabled: true
 login_attempts_threshold: 2
 trusted_proxies: 172.28.0.6
 use_x_forwarded_for: true
 base_url: !secret base_url
 
light:
  - platform: switch
    name: Kitchen Outer Light
    entity_id: switch.kitchen_outer_lights_switch
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_main_light
      - light.kitchen_outer_light
  - platform: group
    name: Lounge Lights
    entities:
      - light.lounge_iris
      - light.lounge_main_light_level
      - light.lounge
mqtt:
  broker: 192.168.86.51
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

plant:
  chillies:
    sensors:
      temperature: sensor.greenhouse_temperature
      brightness: sensor.greenhouse_light
    min_temperature: 5
    
    
recorder:  
  purge_keep_days: 2 
  db_url: !secret sql

remote:
  - platform: huesensor

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

tplink:    

transmission:
  host: !secret seedbox
  username: !secret transmission_username
  password: !secret transmission_password
    
tts:
  - platform: microsoft
    api_key: !secret microsoft_tts_key

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_key

weather:
  - platform: darksky
    api_key: !secret darksky
  

influxdb:
  host: 192.168.86.51
  database: homeassistant

hacs:
  token: !secret git_token

sentry:
  dsn: !secret sentry

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret


withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  profiles:
    - Ross
    
input_boolean:
  winter:
    name: Disable the greenhouse alerts in the winter
    icon: mdi:thermometer-chevron-down
    
input_number:
  kitchen_light_level:
    name: Kitchen light level
    min: 0
    max: 150
    step: 1    
    unit_of_measurement: 'lx'
  hall_light_level:
    name: Hall light level
    min: 0
    max: 150
    step: 1    
    unit_of_measurement: 'lx'    
