homeassistant:  
  name: Home  
  latitude: !secret latitude
  longitude: !secret longitude  
  elevation: 30  
  unit_system: metric  
  time_zone: Europe/London
  customize: !include configuration/customize.yaml  
  packages: !include_dir_named configuration/packages/

###################################################################################
# Standard configuration
###################################################################################
cloud:
  alexa:
    entity_config:
      switch.hall_main_light_switch:
        display_categories: 'LIGHT'
        name: 'Hall Light'
      switch.garage_switch:
        name: 'Garage Light'
        display_categories: 'LIGHT'        
      switch.dining_room_floor_lamp_switch:
        name: 'Dining room floor lamp'
        display_categories: 'LIGHT'
      switch.lounge_floor_lamp_switch:
        display_categories: 'LIGHT'
        name: 'Lounge floor lamp'
      switch.bedroom_tv_switch:
        display_categories: 'TV'
        name: 'Bedroom TV'
      switch.lounge_tv_switch:
        display_categories: 'TV'
        name: 'Lounge Tv'
      switch.electric_blanket_switch:
        display_categories: 'SMARTPLUG'
        name: 'Electric Blanket'
      switch.kitchen_outer_lights_switch:
        display_categories: 'LIGHT'
        name: 'Kitchen outer lights'
    filter:      
      include_entities:
        - light.kitchen_main_light_level
        - light.lounge_main_light_level
        - light.bedroom_main_light_level
        - media_player.shield
      include_domains:
        - switch
      exclude_entities:
        - switch.garage_switch_2
        - switch.dead_switch
        - switch.dead_switch_2
        - switch.dead_switch_3

config:
discovery:
history:
ios:
logbook:
map:
sun:
updater:

###################################################################################
# Group configurations
###################################################################################
automation: !include_dir_merge_list configuration/automation
alexa: !include configuration/alexa/alexa.yaml
alert: !include_dir_merge_named configuration/alert
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include configuration/groups.yaml
intent_script: !include_dir_merge_named configuration/alexa/intent_script/ 
media_player: !include_dir_merge_list configuration/media_player
notify: !include configuration/notify.yaml
panel_iframe: !include configuration/panel_iframe.yaml
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensors
timer: !include configuration/timer.yaml
zone: !include configuration/zones.yaml

####################################################################################
# Additional Configurations
####################################################################################

camera:
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil08.jpg?
    name: A1
  - platform: ring

device_tracker:
  - platform: owntracks
    secret: !secret owntracks
  - platform: icloud
    username: !secret apple_username
    password: !secret apple_password
    account_name: Apple








frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html
    
google_assistant:
  project_id: homeassistant-de3c6
  client_id: bTF5sTbZATEo3opT3h6BspxZVAvd7Ed86r5iNy0hrc9QgPKpe0NXsoabpjUwFqt8z62H1rE9zFod0aaL
  access_token: !secret google_access_token
  exposed_domains:
    - switch
    - light
    - group     
hue:
  bridges:
    - host: 192.168.86.31
http:
 api_password: !secret api_password
 
light:
  - platform: hue
    allow_in_emulated_hue: false
mqtt:
  broker: 192.168.86.54
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

recorder:
  purge_interval: 2
  purge_keep_days: 5 

ring:
  username: !secret ring_username
  password: !secret ring_password
  
#switch:
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/grafana
#    name: Grafana
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/alarm-mqtt
#    name: Alarm Mqtt
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/openhab-findwifesphone
#    name: Find Kaths Phone
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/alarm-watchdog
#    name: Alarm Watchdog
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/influxdb
#    name: Influx DB
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/travis
#    name: Travis Webhook
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/pihole
#    name: Pi Hole
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/alarm-daemon
#    name: Alarm Daemon
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/openvpn
#    name: Open VPN
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'


tts:
  - platform: google
  - platform: microsoft
    api_key: !secret microsoft_tts_key

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_key
  
  
# Commenting out because of the issues
#influxdb:
#  host: 192.168.86.54
#  database: homeassistant
