homeassistant:  
  name: Home  
  latitude: !secret latitude
  longitude: !secret longitude  
  elevation: 30  
  unit_system: metric  
  time_zone: Europe/London
  customize: !include configuration/customize.yaml  
  packages: !include_dir_named configuration/packages/
  auth_providers:
   - type: homeassistant  
   - type: legacy_api_password


###################################################################################
# Standard configuration
###################################################################################
emulated_roku:
  host_ip: 192.168.86.54 # should be set to Home Assistant's address

cloud:
  alexa:
    entity_config:
      switch.hall_main_light_switch:
        display_categories: 'LIGHT'
        name: 'Hall Light'
      switch.garage_switch:
        name: 'Garage Light'
        display_categories: 'LIGHT'        
      switch.dining_room_floor_lamp_switch:
        name: 'Dining room floor lamp'
        display_categories: 'LIGHT'
      switch.lounge_floor_lamp_switch:
        display_categories: 'LIGHT'
        name: 'Lounge floor lamp'
      switch.bedroom_tv_switch:
        display_categories: 'TV'
        name: 'Bedroom TV'
      switch.lounge_tv_switch:
        display_categories: 'TV'
        name: 'Lounge Tv'
      switch.electric_blanket_switch:
        display_categories: 'SMARTPLUG'
        name: 'Electric Blanket'
      switch.kitchen_outer_lights_switch:
        display_categories: 'LIGHT'
        name: 'Kitchen outer lights'
    filter:      
      include_entities:
        - light.kitchen_main_light_level
        - light.lounge_main_light_level
        - light.bedroom_main_light_level
        - media_player.shield        
      include_domains:
        - switch
        - lock
      exclude_entities:
        - switch.garage_switch_2
        - switch.dead_switch
        - switch.dead_switch_2
        - switch.dead_switch_3

config:
discovery:
history:
ios:
logbook:
map:
sun:
updater:
auth:

###################################################################################
# Group configurations
###################################################################################
automation: !include_dir_merge_list configuration/automation
alexa: !include configuration/alexa/alexa.yaml
alert: !include_dir_merge_named configuration/alert
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include configuration/groups.yaml
intent_script: !include_dir_merge_named configuration/alexa/intent_script/ 
media_player: !include_dir_merge_list configuration/media_player
notify: !include configuration/notify.yaml
panel_iframe: !include configuration/panel_iframe.yaml
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensors
timer: !include configuration/timer.yaml
zone: !include configuration/zones.yaml

####################################################################################
# Additional Configurations
####################################################################################
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

homekit:
  pincode: !secret homekit
  entity_config:
    alarm_control_panel.alarm:
      code: !secret pin
  filter:
    exclude_domains:
      - automation
    exclude_entities:
      - binary_sensor.greenhouse_resevoir
#android_ip_webcam:
#  - host: 192.168.86.35
#    port: 8080
#    username: admin
#    password: !secret webcam_password
#    name: Front
#    sensors:
#      - audio_connections
#      - battery_level
#      - battery_temp
#      - battery_voltage
#      - light
#      - motion
#      - pressure
#      - proximity
#      - sound
#      - video_connections
#    switches:
#      - exposure_lock
#      - ffc
#      - focus
#      - gps_active
#      - night_vision
#      - overlay
#      - torch
#      - whitebalance_lock
#      - video_recording      
camera:
  - platform: generic
    still_image_url: https://liveimages.networkwebcams.co.uk/sd_durhamcouncil08.jpg?
    name: A1
  - platform: ring
  
custom_updater:
  component_urls:
  - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  - https://raw.githubusercontent.com/custom-components/information/master/repos.json
  
calendar:
  - platform: todoist
    token: !secret todoist
    
device_tracker:
#  - platform: owntracks
#    secret: !secret owntracks
  - platform: icloud
    username: !secret apple_username
    password: !secret apple_password
    account_name: Apple
  - platform: google_maps
    username: !secret google_username
    password: !secret google_password






frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html

history_graph:
  temp:
    name: Temperature Graph
    entities:
      - sensor.greenhouse_temperature
      - sensor.hall_temperature
    hours_to_show: 48
    refresh: 60
    
hue:
  bridges:
    - host: 192.168.86.31
http:
 api_password: !secret api_password
 ip_ban_enabled: true
 login_attempts_threshold: 2
 trusted_proxies: 192.168.86.51
 use_x_forwarded_for: true
 
light:
  - platform: hue
    allow_in_emulated_hue: false
  - platform: group
    name: Lounge Lights
    entities:
      - light.lounge_iris
      - light.lounge_main_light_level
      - light.lounge
mqtt:
  broker: 192.168.86.54
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_secret

plant:
  chillies:
    sensors:
      temperature: sensor.greenhouse_temperature
      brightness: sensor.greenhouse_light
    min_temperature: 5
    
    
recorder:
  purge_interval: 2
  purge_keep_days: 5 

ring:
  username: !secret ring_username
  password: !secret ring_password
  
#switch:
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/grafana
#    name: Grafana
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/alarm-mqtt
#    name: Alarm Mqtt
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/openhab-findwifesphone
#    name: Find Kaths Phone
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/alarm-watchdog
#    name: Alarm Watchdog
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/influxdb
#    name: Influx DB
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/travis
#    name: Travis Webhook
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/pihole
#    name: Pi Hole
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/alarm-daemon
#    name: Alarm Daemon
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#  - platform: rest
#    resource: http://192.168.86.54:8126/container/openvpn
#    name: Open VPN
#    body_on: '{"state": "start"}'
#    body_off: '{"state": "stop"}'
#    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'


tts:
  - platform: google
  - platform: microsoft
    api_key: !secret microsoft_tts_key

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_key

weather:
  - platform: darksky
    api_key: !secret darksky
  

influxdb:
  host: 192.168.86.54
  database: homeassistant
