name: My Awesome Home
resources:
  - url: /local/tracker-card.js?v=0
    type: js
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - tab_icon: mdi:home
    name: Home
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
      - type: picture-glance
        image: /local/diningroom.jpg
        title: Dining Room
        entities:
          - binary_sensor.dining_room_pir
          - switch.dining_room_floor_lamp_switch
          - light.diningroom
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
      - type: entity-picture
        image: /local/diningroom.jpg
        entity: light.diningroom
        title: Dining Room
        # The entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        entities:
          - alarm_control_panel.alarm
          - binary_sensor.greenhouse_resevoir
          - input_boolean.switch_tv
          - sensor.ross_monzo
          - camera.front_door
          - plant.chillies
      - type: plant-status
        entity: plant.chillies
      - type: camera-preview
        entity: camera.front_door
      - type: glance
        entities:
          - alarm_control_panel.alarm
          - binary_sensor.greenhouse_resevoir
          - input_boolean.switch_tv
          - sensor.ross_monzo
          - camera.front_door
      - type: history-graph
        entity: history-graph.temperature_graph
      - type: media-control
        entity: media_player.spotify
      - type: weather-forecast
        entity: weather.dark_sky

    # Specify a tab_icon if you want the view tab to be an icon.
  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    name: Second view
    cards:
      - type: entities
        title: Lots of Kitchen
        entities:
            # It is totally possible to render duplicates.
            - switch.kitchen_outer_lights_switch
            - light.kitchen_hue
            - light.kitchen_main_light_level
