name: My Awesome Home
resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js    
  - url: /local/custom-lovelace/monster-card/monster-card.js
    type: js        
  - url: /local/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js
    type: js         
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=1
    type: module    
  - url: /local/custom-lovelace/mini-graph-card/mini-graph-card.js
    type: module
views:
  - icon: mdi:home
    id: home
    cards:
      - type: picture-glance
        image: /local/lounge.jpg
        title: Lounge
        navigation_path: lounge
        entities:
          - binary_sensor.lounge_pir
          - light.lounge_main_light_level
          - light.lounge_iris
          - light.lounge_lamp
          - switch.lounge_floor_lamp_switch      
          - switch.lounge_tv_switch    
          - switch.lounge_sentsy_switch          
      - type: picture-glance
        image: /local/diningroom.jpg
        title: Dining Room
        entities:
          - binary_sensor.dining_room_pir
          - switch.dining_room_floor_lamp_switch
          - light.diningroom          
      - type: picture-glance      
        image: /local/kitchen.jpg
        title: Kitchen      
        entities:
          - binary_sensor.kitchen_pir
      - type: picture-glance
        image: /local/office.jpg
        title: Office
        entities:
          - binary_sensor.office_pir        
      - type: picture-glance
        image: /local/playroom.jpg
        title: Playroom         
        entities:
          - binary_sensor.playroom_pir      
      - type: picture-glance
        image: /local/hall.jpg
        title: Hall         
        entities:
          - binary_sensor.hall_pir                            
  - icon: mdi:sofa
    id: lounge
    title: Lounge
    cards:            
      - type: media-control
        entity: media_player.spotify    
      - type: media-control      
        entity: media_player.yamaha_reciever
      - type: media-control
        entity: media_player.shield
      - type: media-control
        entity: media_player.plex_d46e7ce32731388a_com_plexapp_android                
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.lounge_main_light_level
          - light.lounge_iris
          - light.lounge_lamp
          - switch.lounge_floor_lamp_switch
      - type: custom:thermostat-card
        entity:  climate.living_room    
      - type: picture-entity
        entity: switch.lounge_sentsy_switch
        image: /local/scentsy.png
        tap_action: toggle
        name: Sentsy
 

    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - tab_icon: mdi:home
    title: Batteries
    cards:
      - type: gauge
        entity: sensor.front_door_battery
        title: Front Door
        unit_of_measurement: '%'
        severity:
          green: 50
          yellow: 25
          red: 0
      - type: gauge
        entity: sensor.ring_front_door_battery
        title: Doorbell
        unit_of_measurement: '%'
        severity:
          green: 50
          yellow: 25
          red: 0          
  - tab_icon: mdi:home
    title: Home
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    cards:
      
      - type: sensor
        entity: sensor.speedtest_download
        line_width: 4
        color: '#3498db'             

      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Lights On
        filter:
          include:
            - domain: light
              state: 'on'        
      # - type: custom:alarm_control_panel-card
      #   entity: alarm_control_panel.alarm
      #   show_keypad: true
      #   title: My Alarm
      #   # auto_enter: true
      #   # code_length: 4
      #   # arm_action: arm_away
      #   states:
      #     - arm_home
      #     - arm_away
      #     - arm_night         
      - type: picture-entity
        image: /local/diningroom.jpg
        entity: light.diningroom
        title: Dining Room
        # The entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        entities:
          - alarm_control_panel.alarm
          - binary_sensor.greenhouse_resevoir          
          - sensor.ross_monzo
          - camera.front_door
          - plant.chillies
      - type: plant-status
        entity: plant.chillies
      - type: picture-glance
        entities: 
         - camera.front_door
        camera_image: camera.front_door
      - type: picture-glance
        entities: 
         - camera.garden
        camera_image: camera.garden
      - type: glance
        entities:
          - alarm_control_panel.alarm
          - binary_sensor.greenhouse_resevoir
          - input_boolean.switch_tv
          - sensor.ross_monzo
          - camera.front_door
      - type: history-graph
        entities: 
          - history_graph.temperature_graph
      - type: media-control
        entity: media_player.spotify
      - type: weather-forecast
        entity: weather.dark_sky
      - type: map
        aspect_ratio: 100%
        entities:         
          - device_tracker.google_maps_104113982427948631716
          - device_tracker.iphone

  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    title: Media
    cards:
      - type: custom:upcoming-media-card
        service: sonarr  


    # Specify a tab_icon if you want the view tab to be an icon.
  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    title: Settings
    cards:
      - type: custom:tracker-card
        title: test
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker          
