name: My Awesome Home
resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js    
  - url: /local/custom-lovelace/monster-card/monster-card.js
    type: js        
  - url: /local/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js
    type: js         
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=1
    type: module    
  - url: /local/custom-lovelace/mini-graph-card.js
    type: module
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - tab_icon: mdi:home
    title: Home
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    cards:
      - type: picture-glance
        image: /local/diningroom.jpg
        title: Dining Room
        entities:
          - binary_sensor.dining_room_pir
          - switch.dining_room_floor_lamp_switch
          - light.diningroom
      - type: custom:mini-graph-card
        entity: sensor.front_door_battery
        height: 100
        line_width: 4
        color: '#3498db'          
      - type: custom:thermostat-card
        title: Lounge
        entity:  climate.living_room     
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: Lights On
        filter:
          include:
            - domain: light
              state: 'on'        
      # - type: custom:alarm_control_panel-card
      #   entity: alarm_control_panel.alarm
      #   show_keypad: true
      #   title: My Alarm
      #   # auto_enter: true
      #   # code_length: 4
      #   # arm_action: arm_away
      #   states:
      #     - arm_home
      #     - arm_away
      #     - arm_night         
      - type: picture-entity
        image: /local/diningroom.jpg
        entity: light.diningroom
        title: Dining Room
        # The entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        entities:
          - alarm_control_panel.alarm
          - binary_sensor.greenhouse_resevoir          
          - sensor.ross_monzo
          - camera.front_door
          - plant.chillies
      - type: plant-status
        entity: plant.chillies
      - type: picture-glance
        entities: 
         - camera.front_door
        camera_image: camera.front_door
      - type: picture-glance
        entities: 
         - camera.garden
        camera_image: camera.garden
      - type: glance
        entities:
          - alarm_control_panel.alarm
          - binary_sensor.greenhouse_resevoir
          - input_boolean.switch_tv
          - sensor.ross_monzo
          - camera.front_door
      - type: history-graph
        entities: 
          - history_graph.temperature_graph
      - type: media-control
        entity: media_player.spotify
      - type: weather-forecast
        entity: weather.dark_sky
      - type: map
        aspect_ratio: 100%
        entities:         
          - device_tracker.google_maps_104113982427948631716
          - device_tracker.kathsiphone

  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    title: Media
    cards:
      - type: custom:upcoming-media-card
        service: sonarr  


    # Specify a tab_icon if you want the view tab to be an icon.
  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    title: Settings
    cards:
      - type: custom:tracker-card
        title: test
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker          
