- alias: Lounge PIR Timeout
  trigger:
    - platform: state
      entity_id: binary_sensor.loung_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Lounge
      payload: Close

- alias: Office PIR Timeout
  trigger:
    - platform: state
      entity_id: binary_sensor.office_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Office
      payload: Close

- alias: Dining Room PIR Timeout
  trigger:
    - platform: state
      entity_id: binary_sensor.dining_room_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Dining Room
      payload: Close

- alias: Hall PIR Timeout
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Hall
      payload: Close      

- alias: Kitchen PIR Timeout
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'on'
      for:
        minutes: 4
  action:
    - service: mqtt.publish
      data:
        topic: alarm/events/PIR/Playroom
        payload: Close      
    - service: light.turn_on
        entity_id: 
        - light.kitchen_hue
        data:
          transition: 10
