- alias: Close all pirs on startup
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: script.turn_off_all_pir

- alias: Lounge PIR Timeout
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.loung_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Lounge
      payload: Close

- alias: Office PIR Timeout
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.office_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Office
      payload: Close

- alias: Dining Room PIR Timeout
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.dining_room_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Dining Room
      payload: Close

- alias: Hall PIR Timeout
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_pir
      to: 'on'
      for:
        minutes: 4
  action:
    service: mqtt.publish
    data:
      topic: alarm/events/PIR/Hall
      payload: Close      

- alias: Kitchen PIR Timeout
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'on'
      for:
        minutes: 4
  action:
    - service: mqtt.publish
      data:
        topic: alarm/events/PIR/Playroom
        payload: Close
