alarm_control_panel:
  platform: mqtt
  state_topic: "alarm/state"
  command_topic: "alarm/mode"
  name: "Alarm"
  payload_disarm: "Disarm"
  payload_arm_home: "Home"
  payload_arm_away: "Away"
  code: !secret pin

###################################################
# Notification for the alarm going off
###################################################
alert:
  burglar_alarm:
    name: Burglar Alarm
    entity_id: alarm_control_panel.alarm
    state: 'triggered'
    repeat: 5
    can_acknowledge: True
    skip_first: False
    notifiers:
      - slackbot
      - html5
    #  - html5_ross_phone

###################################################
# Display the last alarm state
###################################################
sensor:
  - platform: mqtt
    name: "Alarm Events"
    state_topic: "alarm/events"
#######################################################
# Display the actual alarm mode directly from the alarm
#######################################################
  - platform: rest
    name: "Alarm State"
    resource: http://192.168.86.51:8126/container/alarm-watchdog/exec
    method: POST
    headers: 
      content-type: application/octet-stream
    payload: '{"command":"./bin/get-mode.pl"}'
    value_template: '{{ value_json.result | trim }}'

automation:
###################################################
# Notify when the alarm is armed/disarmed with a fob
###################################################
  - alias: Alarm Remote Fob pressed
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: alarm/events/Remote Control/+
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.ha_alarm 
      - service: script.alarm_messages
        data_template:
         action: '{{ trigger.payload }}'
         name: '{{ trigger.topic.replace("alarm/events/Remote Control/","").replace(" Fob", "").replace("Kaths","Kath") }}'
###################################################
# Detect the alarm being triggererd
###################################################
  - alias: Alarm Triggered
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: alarm/events
      payload: 'Burglary'
    action:
      - service: mqtt.publish
        data_template:
          topic: 'alarm/state'
          payload: 'triggered'
          retain: true
      - service: alarm_control_panel.alarm_trigger # trigger the manual alarm now...
        entity_id: alarm_control_panel.ha_alarm
###################################################
# Turn off the PIRs when HASS starts up.
# If a PIR is on, and HASS restarts it will never be turned off.
###################################################
  - alias: Close all pirs on startup
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: script.turn_off_all_pir

###################################################
# PIR time outs
###################################################
  - alias: Lounge PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.loung_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Lounge
        payload: Close

  - alias: Office PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.office_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Office
        payload: Close

  - alias: Dining Room PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.dining_room_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Dining Room
        payload: Close

  - alias: Hall PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Hall
        payload: Close      

  - alias: Kitchen PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
        for:
          minutes: 4
    action:
      - service: mqtt.publish
        data:
          topic: alarm/events/PIR/Playroom
          payload: Close

###################################################
# The PIR sensors
###################################################
binary_sensor:
  - platform: mqtt
    state_topic: "alarm/events/PIR/Office"
    name: "Office PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Lounge"
    name: "Lounge PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Hall"
    name: "Hall PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Kitchen"
    name: "Kitchen PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Dining Room"
    name: "Dining Room PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion    
  - platform: mqtt
    state_topic: "alarm/events/Door Switch/Garage Door"
    name: "Garage Door"    
    payload_on: "Open"
    payload_off: "Close"
    device_class: opening
  - platform: mqtt
    state_topic: "alarm/events/Door Switch/Front Door"
    name: "Front Door"    
    payload_on: "Open"
    payload_off: "Close"
    device_class: opening
  - platform: mqtt
    state_topic: "alarm/events/Door Switch/Playroom Door"
    name: "Playroom Door"    
    payload_on: "Open"
    payload_off: "Close"
    device_class: opening

script:
 #############################################################################################
 # Turns all the PIRs off
 #############################################################################################
  turn_off_all_pir:
    alias: 'Turn off all the PIRs - might not be needed'
    sequence:
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Office
       payload: Close
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Lounge
       payload: Close     
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Hall
       payload: Close    
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Kitchen
       payload: Close     
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Dining Room
       payload: Close    

###################################################
# Notify when the arm mode is changed
###################################################
  alarm_messages:
    alias: '_Notify when a the alarm mode is changed'
    sequence:
    - service: mqtt.publish
      data_template:
        topic: 'alarm/state'
        payload_template: '{{ action.replace(" Mode", "").replace(" mode", "").replace("Disarm","disarmed").replace("Away","armed_away").replace("Home", "armed_home") }}'
        retain: true    
   # - service: notify.iphone
   #   data_template:
   #     title: 'Alarm {{action}}'
   #     message: 'Alarm put in {{ action }} by {{ name }}'
    - service: notify.html5
      data_template:
        title: 'Alarm {{action}}'
        message: 'Alarm put in {{ action }} by {{ name }}'
        data:
          icon: "https://www.the-dargans.co.uk/local/{{ name|lower }}.png"
          tag: 'alarm'   


###################################################
# Alarm sensor groups
###################################################
group:
  alarm_sensors:
    name: Alarm Sensors
    entities:
      - binary_sensor.ring_front_door_motion # not technically an alarm sensor...
      - binary_sensor.dining_room_pir
      - binary_sensor.office_pir
      - binary_sensor.hall_pir
      - binary_sensor.lounge_pir
      - binary_sensor.kitchen_pir
      - binary_sensor.front_door
      - binary_sensor.playroom_door
      - binary_sensor.garage_door
      - sensor.alarm_events
