###################################################
# Notification for the alarm going off
###################################################

alert:
  burglar_alarm:
    name: Burglar Alarm
    entity_id: alarm_control_panel.alarm
    state: 'triggered'
    repeat: 5
    can_acknowledge: True
    skip_first: False
    notifiers:
      - slackbot
      - ios_kaths_iphone
      - html5_ross_phone

sensor:
  - platform: mqtt
    name: "Alarm Events"
    state_topic: "alarm/events"

automation:
  - alias: Alarm Remote Fob pressed
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: alarm/events/Remote Control/+
    action:
      - service: script.alarm_messages
        data_template:
         action: '{{ trigger.payload }}'
         name: '{{ trigger.topic.replace("alarm/events/Remote Control/","").replace(" Fob", "").replace("Kaths","Kath") }}'
 #     - service: mqtt.publish
 #       data:
 #        topic: {{ trigger.topic }}
 #        payload: ''
 #        retain: true  
  - alias: Alarm Triggered
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: alarm/events
      payload: 'Burglary'
    action:
      - service: mqtt.publish
        data_template:
          topic: 'alarm/state'
          payload: 'triggered'
          retain: true

  - alias: Close all pirs on startup
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: script.turn_off_all_pir

  - alias: Lounge PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.loung_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Lounge
        payload: Close

  - alias: Office PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.office_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Office
        payload: Close

  - alias: Dining Room PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.dining_room_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Dining Room
        payload: Close

  - alias: Hall PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_pir
        to: 'on'
        for:
          minutes: 4
    action:
      service: mqtt.publish
      data:
        topic: alarm/events/PIR/Hall
        payload: Close      

  - alias: Kitchen PIR Timeout
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_pir
        to: 'on'
        for:
          minutes: 4
    action:
      - service: mqtt.publish
        data:
          topic: alarm/events/PIR/Playroom
          payload: Close

binary_sensor:
  - platform: mqtt
    state_topic: "alarm/events/PIR/Office"
    name: "Office PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Lounge"
    name: "Lounge PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Hall"
    name: "Hall PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Kitchen"
    name: "Kitchen PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion
  - platform: mqtt
    state_topic: "alarm/events/PIR/Dining Room"
    name: "Dining Room PIR"    
    payload_on: "Trigger"
    payload_off: "Close"
    device_class: motion    
  - platform: mqtt
    state_topic: "alarm/events/Door Switch/Garage Door"
    name: "Garage Door"    
    payload_on: "Open"
    payload_off: "Close"
    device_class: opening
  - platform: mqtt
    state_topic: "alarm/events/Door Switch/Front Door"
    name: "Front Door"    
    payload_on: "Open"
    payload_off: "Close"
    device_class: opening
  - platform: mqtt
    state_topic: "alarm/events/Door Switch/Playroom Door"
    name: "Playroom Door"    
    payload_on: "Open"
    payload_off: "Close"
    device_class: opening

script
 #############################################################################################
 # Need to turn of all PIRs because if it was on after a reboot it will never get turned off #
 #############################################################################################
  turn_off_all_pir:
    alias: 'Turn off all the PIRs - might not be needed'
    sequence:
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Office
       payload: Close
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Lounge
       payload: Close     
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Hall
       payload: Close    
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Kitchen
       payload: Close     
    - service: mqtt.publish
      data:
       topic: alarm/events/PIR/Dining Room
       payload: Close    
       
  alarm_messages:
    alias: '_Notify when a the alarm mode is changed'
    sequence:
    - service: notify.slackbot
      data_template:
        message: 'Alarm put in {{ action }} by {{ name }}'
    - service: notify.ios_kaths_iphone
      data_template:
        title: 'Alarm {{action}}'
        message: 'Alarm put in {{ action }} by {{ name }}'
    - service: notify.html5
      data_template:
        title: 'Alarm {{action}}'
        message: 'Alarm put in {{ action }} by {{ name }}'
        data:
          icon: "https://www.the-dargans.co.uk/local/{{ name|lower }}.png"
          tag: 'alarm'
    - service: mqtt.publish
      data_template:
        topic: 'alarm/state'
        payload_template: '{{ action.replace(" Mode", "").replace(" mode", "").replace("Disarm","disarmed").replace("Away","armed_away").replace("Home", "armed_home") }}'
        retain: true
