alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    code: !secret pin
    code_arm_required: false    
    armed_away:
      delay_time: 20 # 20 seconds to disarm the alarm
      pending_time: 30 # 10 seconds to leave...
    armed_home:
      delay_time: 60 # 60 seconds trigger when at home
    triggered:
      pending_time: 0 # no pending time when the alarm is triggered - use the delay time

input_boolean:
  test_mode:
    name: Put the alarm into test mode
    initial: off
    icon: mdi:mdi-volume-off

#################################################
###               Triggers                    ###
#################################################
automation:
- alias: 'Trigger alarm while armed away'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.hall_motion_motion
        - binary_sensor.garage_motion_sensor
        - binary_sensor.office_motion_sensor
        - binary_sensor.lounge_motion_sensor
        - binary_sensor.kitchen_motion_sensor
        - binary_sensor.playroom_motion_sensor
        - binary_sensor.front_door
        - binary_sensor.garage_door
        - binary_sensor.playroom_door
      to: 'on' 
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm

#####################################################
###      Alarm triggered notifications            ###
#####################################################
- alias: 'Send notification when alarm triggered'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  condition:
    - condition: state
      entity_id: input_boolean.test_mode
      state: 'off'     
  action:
    - service: script.alarm_triggered

#########################################################
###                 Alarm Modes Changed               ###
#########################################################
- alias: 'Alarm Arming'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      from: 'disarmed'
      to: 'pending'
  action:
    - service: light.turn_on
      entity_id: light.hall      
      data:
        color_name: "orange"        
        brightness: 255        
    - service: mqtt.publish
      data:
        topic: 'alarmpanel/command'
        payload_template: >
          {"speak":"{% if is_state("lock.office_door", "locked") and is_state("lock.playroom_door", "locked")   -%}
          Yes, all the doors are locked
          {%- elif is_state("lock.office_door", "unlocked") and is_state("lock.playroom_door", "unlocked")  -%}
          All the back doors are not locked
          {%- elif is_state("lock.office_door", "unlocked") %}
          The office door is not locked
          {%- else -%}
          The playroom door is not locked
          {%- endif %}"}#" This is just needed to correct vs code...
    - service: light.turn_on
      entity_id: light.hall
      data:
        color_name: "red"          
        transition: 30
        brightness: 255            

- alias: 'Alarm Armed'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      from: 'pending'
      to: 'armed_away'
  action:
    - service: notify.html5
      data_template:
        title: 'Alarm Armed'
        message: 'The alarm has been armed'           
        data:           
          tag: 'alarm'   
          priority: high        
          url: /lovelace/alarm-test

    - service: light.turn_on
      entity_id: light.hall
      data:        
        color_name: "red"          
        brightness: 30      
    - delay: '00:00:50'
    - service: scene.turn_on
      entity_id: scene.everything_turned_off          

- alias: 'Alarm Deactivated'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'disarmed'
  action:
    - service: notify.html5
      data_template:
        title: 'Alarm Disarmed'
        message: 'The alarm has been disarmed'           
        data:           
          tag: 'alarm'   
          url: /lovelace/alarm-test
          priority: high        
    - service: light.turn_on
      entity_id: light.hall
      data:
        color_name: "green"  
        brightness: 255
    - delay: '00:00:10'
    - service: scene.turn_on
      entity_id: scene.day        

#################### Disarm actions ######################
- alias: Door unlocked
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: lock.front_door
      from: 'locked'
      to: 'unlocked'
    - platform: state
      entity_id: lock.office_door
      from: 'locked'
      to: 'unlocked'
    - platform: state
      entity_id: lock.playroom_door
      from: 'locked'
      to: 'unlocked'                
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret pin


###################Notify when alarm goes off script########
script:
  arm_alarm:
    sequence:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.ha_alarm 
  alarm_triggered:
    sequence:
      - service: switch.turn_on
        entity_id: switch.garden_siren
      - service: switch.turn_on
        entity_id: switch.living_room_siren                  
      - service: notify.html5
        data_template:
          title: 'Alarm Triggered!'
          message: 'The alarm has been triggered'           
          data:           
            tag: 'alarm'     
            priority: high  
            url: /lovelace/alarm-test
            icon:  https://www.the-dargans.co.uk/local/Alert.png
      - service: light.turn_off
        entity_id: all
      - service: light.turn_on
        entity_id: light.downstairs
        data:
          color_name: "red"          
          flash: "long"                                                                                                                                             
      - service: notify.twilio
        data:
          message: "The alarm has been triggered"
          target: !secret ross_mobile_number       
      - service: notify.alexa_media
        data:
          data:
            type: announce
          target: 
            - media_player.dining_room_2
            - media_player.garage
            - media_player.kitchen_2
            - media_player.office_2
            - media_player.playroom_echo
            - media_player.lounge
          message: 'The Alarm has been activated, and the police have been called.'         
      - service: media_player.volume_set
        entity_id: media_player.kitchen_2
        data:
          volume_level: 1           
      - service: media_player.play_media
        entity_id: media_player.kitchen_2 
        data:
          media_content_id: "Warning Alarm Siren 3"
          media_content_type: AMAZON_MUSIC         
