automation:
  - alias: Plex Webhook
    initial_state: 'on'
    trigger:
      platform: webhook
      webhook_id: !secret plex_webhook
    action:
     - service: mqtt.publish
       data_template:
         topic: 'plex/update'
         payload_template: "{{ (trigger.data['payload'] | string)[12:][:-2] }}"
     - service: notify.slackbot
       data_template:
         message: "Original: {{ (trigger.data['payload'] | string)[12:][:-2] }}"

  - alias: Plex Webhook As Json
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: 'plex/update'
    action:
      - service: script.process_plex_message
        data_template:
          event: "{{ trigger.payload_json.event }}"
          player: "{{ trigger.payload_json.Player.title }}"
          account: "{{ trigger.payload_json.Account.title }}"


script:
  process_plex_message:
    sequence:
      - service: notify.slackbot
        data_template:    
          message: "Plex event: {{ event }} - {{ account }} - {{ player }}"

