## A lot of sensors borrowed from here: https://github.com/bl0rp/Home-AssistantConfig/blob/master/packages/systeminfo.yaml#L295

sensor:
##################################################################
### Current HASS Version
###################################################################
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current HASS Version

##################################################################
### Installed HASS Version
###################################################################
  -  platform: command_line
     command: python -m homeassistant --version
     name: Installed HASS Version

##################################################################
### HASS Update Available
###################################################################
  - platform: template
    sensors:
      hass_update_available:
        friendly_name: 'HASS Update Available'
        value_template: >-
          {%- if states.sensor.current_hass_version.state != states.sensor.installed_hass_version.state -%}
             Yes
          {%- else -%}
             No
          {%- endif -%}
          
###### CUSTOM HA/Version
  - platform: template
    sensors:
      ha_version:
        value_template: "{%- if states.sensor.ha_release.state == states.sensor.ha_release_local.state-%} Ja! {% else %}{{states.sensor.ha_release.state}} verfügbar! {% endif%}"
        icon_template: >-
          {% if states.sensor.ha_release.state == states.sensor.ha_release_local.state %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}
          
          
##################################################################
### Uptime for the server
###################################################################
  - platform: command_line
    name: host_uptime_in_seconds
    command: "awk '{print $1}' /proc/uptime"
    unit_of_measurement: "sec"
    value_template: '{{ value|round }}'

  - platform: template
    sensors:
      host_uptime_human:
        value_template: >-
           {% macro human_time(second) -%}
             {%- set second = second|int -%}
             {%- set comma = joiner(', ') -%}
             {%- set intervals = {
               'week': 60 * 60 * 24 * 7,
               'day': 60 * 60 * 24,
               'hour': 60 * 60,
               'minute': 60,
               'second': 1,
             } -%}
             {%- set week = second // intervals.week -%}
             {%- set second = second % intervals.week -%}
             {{- comma() ~ week ~ ' Week' ~ ('n' if week != 1) if week -}}
             {%- set day = second // intervals.day -%}
             {%- set second = second % intervals.day -%}
             {{- comma() ~ day ~ ' Day' ~ ('e' if day != 1) if day -}}
             {%- set hour = second // intervals.hour -%}
             {%- set second = second % intervals.hour -%}
             {{- comma() ~ hour ~ ' Hour' ~ ('n' if hour != 1) if hour -}}
             {%- set minute = second // intervals.minute -%}
             {{- comma() ~ minute ~ ' Minute' ~ ('n' if minute != 1) if minute -}}
             {%- set second = second % intervals.minute -%}
             {{- comma() ~ second ~ ' Second' ~ ('n' if second != 1) if second -}}
           {%- endmacro %}
           {{ human_time(states.sensor.host_uptime_in_seconds.state | int ) }}       
        
automation:
  - alias: New version available
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.hass_update_available
        to: 'Yes'
        from: 'No'
    action:
      service: calendar.todoist_new_task
      data:
        content: "Upgrade Home assistant {{ states.sensor.current_hass_version.state }}"
        project: 'Personal'
        priority: 3
        due_date_string: 'Today'
