sensor:
##################################################################
### Current HASS Version
###################################################################
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current HASS Version

##################################################################
### Installed HASS Version
###################################################################
  -  platform: command_line
     command: python -m homeassistant --version
     name: Installed HASS Version

##################################################################
### HASS Update Available
###################################################################
  - platform: template
    sensors:
      hass_update_available:
        friendly_name: 'HASS Update Available'
        value_template: >-
          {%- if states.sensor.current_hass_version.state != states.sensor.installed_hass_version.state -%}
             {{ states.sensor.current_hass_version.state }}
          {%- else -%}
             No
          {%- endif -%}
