sensor:
##################################################################
### Current HASS Version
###################################################################
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current HASS Version

##################################################################
### Installed HASS Version
###################################################################
  -  platform: command_line
     command: python -m homeassistant --version
     name: Installed HASS Version

##################################################################
### HASS Update Available
###################################################################
  - platform: template
    sensors:
      hass_update_available:
        friendly_name: 'HASS Update Available'
        value_template: >-
          {%- if states.sensor.current_hass_version.state != states.sensor.installed_hass_version.state -%}
             Yes
          {%- else -%}
             No
          {%- endif -%}
          
          
automation:
  - alias: New version available
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.hass_update_available
        to: 'Yes'
        from: 'No'
    action:
      service: calendar.todoist_new_task
      data:
        content: "Upgrade Home assistant"
        project: 'Personal'
        priority: 3
        due_date_string: 'Today'
