pyscript:
  apps:
    barcode_lookup: 
      cache_csv: pyscript/apps/barcode_lookup/cache.csv # Caching can be disabled by removing the path to a cache file
      off_url_base: https://world.openfoodfacts.org/api/v2/product/ # OpenFoodFacts.org API base path
      upcdb_url_base: https://api.upcdatabase.org/product/ #UPCDatabase.org API base path
      upcdb_api_key: !secret upcdb_api #UPCDatabase.org API key. Can be included from HA secrets.yaml file