- alias: Plex Webhook
  initial_state: 'on'
  trigger:
    platform: webhook
    webhook_id: !secret plex_webhook
  action:
    service_template: notify.slackbot
    data_template: 
      message: "{{ (trigger.json }}"
