- alias: Plex Webhook
  initial_state: 'on'
  trigger:
    platform: webhook
    webhook_id: !secret plex_webhook
  action:
    service: input_text.set_value
    data_template: 
      value: "{{ (trigger.data['payload'] | string)[12:][:-2] }}"
      entity_id: input_text.plex_state
