- platform: template
  sensors: 
    coffee_machine:
      friendly_name: Coffee Ready
      value_template: >
        {{ states.sensor.coffee_machine.state | float > 0 and states.sensor.coffee_machine.state | float < 2 }}      
      icon_template: >
        {% if is_state("binary_sensor.coffee_machine", "on") %}
          mdi:coffee
        {% else %}
          mdi:coffee-off
        {% endif %}