- platform: template
  sensors: 
    coffee_machine:
      friendly_name: Coffee Ready
      value_template: >
        {{ is_state("switch.coffee_machine", "on") }}
      delay_on: "00:01:00"
      icon_template: >
        {% if is_state("binary_sensor.coffee_machine", "on") %}
          mdi:coffee
        {% else %}
          mdi:coffee-off
        {% endif %}