- platform: template
  washing_machine:
    friendly_name: Washing machine
    value_template: >
      {{ states("sensor.lds_zb_onoffplug_d0005_9973cefe_electrical_measurement") | float(0) > 3 }}
    delay_off: "00:05:00"
    icon_template: >
      {% if is_state("binary_sensor.washing_machine", "on") %}
        mdi:washing-machine
      {% else %}
        mdi:washing-machine-off
      {% endif %}

- platform: template
  tumble_dryer:
    friendly_name: Tumble Dryer
    value_template: >
      {{ states("sensor.tumble_dryer_power") | float(0) > 3 }}
    delay_off: "00:05:00"
    icon_template: >
      {% if is_state("binary_sensor.tumble_dryer", "on") %}
        mdi:tumble-dryer
      {% else %}
        mdi:tumble-dryer-off
      {% endif %}    